#!/usr/bin/bash

config_path=$HOME/.config/matlab
dir_to_open=$PWD
matlab_exec=matlab

usage(){
    echo "$0 [DIR] [-o]"
}

# Parse opening dir
if [ -d "$1" ]; then 
    dir_to_open=$1
    shit
fi
# move to next argument

echo "using arguments: $@ -r cd ${dir_to_open}"

# Open correctly
cd $config_path
matlab $@ -r "cd ${dir_to_open}"
cd -
