#!/usr/bin/bash

dir_to_open=$PWD
config_path=$HOME/.config/matlab
matlab_exec=$HOME/.local/var/matlab_2024a/bin/matlab

usage(){
    echo "$0 [DIR] [-o]"
}

# Parse opening dir
if [ -d "$1" ]; then 
    dir_to_open=$1
    shit
fi
# move to next argument

echo "using arguments: $@ -r cd ${dir_to_open}"

# Open correctly
cd $config_path
matlab $@ -r "cd ${dir_to_open}"
cd -
